### PR TITLE
added pileup doc JSON files

### PR DESCRIPTION
**Pull request by akmorrow13**

### CODE REVIEW

**Comment by akmorrow13** [comment]
https://github.com/plotly/dash-docs/pull/1114/files is dependent on this

**Review by HammadTheOne — APPROVED** [review]
Looks good! :woman_dancing:

**Comment by HammadTheOne** [comment]
Feel free to merge this PR if there are no other datasets required for these docs :+1:

**Comment by akmorrow13** [comment]
@HammadTheOne are you asking me to merge? I don't think I have permission.

**Pull request merged**
